name: slack_flutter
description: A package for Slack API
version: 0.1.0+1
publish_to: none

environment:
  sdk: "^3.2.6"
  flutter: "^3.16.9"

dependencies:
  dio: ^5.4.1
  flutter:
    sdk: flutter
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0
